#!/usr/bin/env -S npx tsx

/**
 * Validate generated web app data files.
 *
 * Target: pipeline/build/data/{prefix}/ — the JSON files generated by
 * build-app-data-from-gtfs.ts for the web app.
 *
 * Runs two validation steps:
 * 1. File existence check — verifies all required JSON files exist for
 *    each source.
 * 2. Calendar freshness check — inspects each service's end_date and
 *    reports expired or expiring-soon entries.
 *
 * Output includes both human-readable console logs and a Markdown
 * summary for GitHub Actions Job Summary.
 *
 * Exit codes:
 *   0 — all checks passed
 *   1 — warnings only (e.g. services expiring soon)
 *   2 — errors found (missing files or expired services)
 *
 * Usage:
 *   npx tsx pipeline/scripts/validate-generated-data.ts
 *   npm run pipeline:validate
 */

import { existsSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { loadAllGtfsSources } from '../lib/load-gtfs-sources';
import { runMain } from '../lib/pipeline-utils';

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const ROOT = resolve(import.meta.dirname, '..');
const DATA_DIR = join(ROOT, 'build/data');

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Resolved source info for validation. */
interface ValidateSource {
  prefix: string;
  nameEn: string;
}

interface CalendarService {
  /** Prefixed service ID (e.g. "tobus:01-100") */
  i: string;
  /** Day-of-week flags [mon, tue, wed, thu, fri, sat, sun] */
  d: number[];
  /** Start date in YYYYMMDD format */
  s: string;
  /** End date in YYYYMMDD format */
  e: string;
}

interface CalendarData {
  services: CalendarService[];
  exceptions: unknown[];
}

interface ExpiredEntry {
  source: string;
  serviceId: string;
  endDate: string;
}

interface ExpiringSoonEntry extends ExpiredEntry {
  daysLeft: number;
}

/** Result of file existence check for all sources. */
interface FileCheckResult {
  /** Total number of files checked. */
  total: number;
  /** Number of files that exist. */
  present: number;
  /** Missing files grouped by source prefix. */
  missing: { source: string; file: string }[];
}

/** Result of calendar freshness check for all sources. */
interface CalendarCheckResult {
  /** Total number of services checked across all sources. */
  totalServices: number;
  expired: ExpiredEntry[];
  expiringSoon: ExpiringSoonEntry[];
  /** Number of sources whose calendar.json failed to load. */
  loadErrors: number;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Exit code: all checks passed. */
const EXIT_OK = 0;
/** Exit code: warnings only (e.g. services expiring soon). */
const EXIT_WARN = 1;
/** Exit code: errors found (missing files or expired services). */
const EXIT_ERROR = 2;

const WARN_THRESHOLD_DAYS = 30;

/** Whether running on GitHub Actions (enables workflow commands output). */
const IS_GITHUB_ACTIONS = process.env.GITHUB_ACTIONS === 'true';

/** JSON files that must exist for each source. */
const REQUIRED_FILES = [
  'stops.json',
  'routes.json',
  'calendar.json',
  'timetable.json',
  'shapes.json',
  'agency.json',
  'feed-info.json',
  'translations.json',
] as const;

// ---------------------------------------------------------------------------
// Logging
// ---------------------------------------------------------------------------

/**
 * Sanitize untrusted external data for safe use in GitHub Actions workflow
 * commands. Escapes characters that have special meaning in GHA annotations
 * (`%`, `\r`, `\n`) to prevent workflow command injection.
 *
 * Preserves the original content (including Japanese characters) for
 * readable log output.
 *
 * @see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
 * @param value - Untrusted string to sanitize
 * @returns Escaped string safe for GHA workflow commands
 */
function sanitize(value: string): string {
  return value.replace(/%/g, '%25').replace(/\r/g, '%0D').replace(/\n/g, '%0A');
}

/**
 * Log a warning message. On GitHub Actions, also emits a `::warning::` annotation.
 * @param message - Warning message
 */
function warn(message: string): void {
  console.log(`  ⚠️ ${sanitize(message)}`);
  if (IS_GITHUB_ACTIONS) {
    console.log(`::warning::${sanitize(message)}`);
  }
}

/**
 * Log an error message. On GitHub Actions, also emits an `::error::` annotation.
 * @param message - Error message
 */
function error(message: string): void {
  console.log(`  ❌ ${sanitize(message)}`);
  if (IS_GITHUB_ACTIONS) {
    console.log(`::error::${sanitize(message)}`);
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Parse a YYYYMMDD date string into a Date object (UTC midnight).
 */
function parseDate(yyyymmdd: string): Date {
  const year = parseInt(yyyymmdd.substring(0, 4), 10);
  const month = parseInt(yyyymmdd.substring(4, 6), 10) - 1;
  const day = parseInt(yyyymmdd.substring(6, 8), 10);
  return new Date(Date.UTC(year, month, day));
}

/**
 * Format a Date as YYYY-MM-DD for readable output.
 */
function formatDate(date: Date): string {
  return date.toISOString().substring(0, 10);
}

/**
 * Calculate the number of days between two dates (truncated).
 */
function diffDays(from: Date, to: Date): number {
  return Math.floor((to.getTime() - from.getTime()) / (1000 * 60 * 60 * 24));
}

/**
 * Right-pad a filename with dots to align status text.
 * e.g. "stops.json ......... " (padded to width, followed by a space)
 */
function padWithDots(name: string, width: number): string {
  return (name + ' ').padEnd(width, '.') + ' ';
}

// ---------------------------------------------------------------------------
// Steps
// ---------------------------------------------------------------------------

/**
 * Load GTFS source definitions from resource files.
 * @returns Array of resolved sources with prefix and nameEn.
 */
async function loadSources(): Promise<ValidateSource[]> {
  console.log('Loading source definitions from pipeline/resources/gtfs/...');

  const allDefs = await loadAllGtfsSources();
  const sources: ValidateSource[] = allDefs.map((d) => ({
    prefix: d.pipeline.prefix,
    nameEn: d.resource.nameEn,
  }));

  const prefixes = sources.map((s) => sanitize(s.prefix)).join(', ');
  console.log(`  Found ${sources.length} sources: ${prefixes}\n`);
  return sources;
}

/**
 * Check that all required JSON files exist for each source.
 *
 * @param sources - GTFS resource definitions
 * @returns Aggregated file check result
 */
function checkFileExistence(sources: ValidateSource[]): FileCheckResult {
  const DOT_WIDTH = 20;
  const missing: { source: string; file: string }[] = [];
  let total = 0;
  let present = 0;

  for (const source of sources) {
    console.log(`  ${sanitize(source.prefix)}:`);
    for (const file of REQUIRED_FILES) {
      total++;
      const filePath = join(DATA_DIR, source.prefix, file);
      const exists = existsSync(filePath);
      const status = exists ? 'OK' : 'MISSING';
      if (exists) {
        present++;
      } else {
        missing.push({ source: source.prefix, file });
      }
      console.log(`    ${padWithDots(file, DOT_WIDTH)}${status}`);
    }
  }

  console.log(`  Result: ${present}/${total} files present.`);
  for (const m of missing) {
    error(`Missing required file: ${m.source}/${m.file}`);
  }

  return { total, present, missing };
}

/**
 * Check calendar freshness for all sources.
 * Assumes calendar.json existence is verified by the file existence step;
 * sources whose calendar.json is missing are skipped with a log message.
 *
 * @param sources - GTFS resource definitions
 * @param today - Current date (UTC midnight)
 * @returns Aggregated calendar check result
 */
function checkCalendarFreshness(sources: ValidateSource[], today: Date): CalendarCheckResult {
  let totalServices = 0;
  let loadErrors = 0;
  const allExpired: ExpiredEntry[] = [];
  const allExpiringSoon: ExpiringSoonEntry[] = [];

  for (const source of sources) {
    const calendarPath = join(DATA_DIR, source.prefix, 'calendar.json');

    if (!existsSync(calendarPath)) {
      console.log(`  ${sanitize(source.prefix)} (calendar.json): skipped (file missing)`);
      continue;
    }

    console.log(`  ${sanitize(source.prefix)} (calendar.json):`);

    let calendar: CalendarData;
    try {
      const calendarContent = readFileSync(calendarPath, 'utf-8');
      calendar = JSON.parse(calendarContent) as CalendarData;
    } catch (e) {
      error(`Failed to load ${calendarPath}: ${e instanceof Error ? e.message : String(e)}`);
      loadErrors++;
      continue;
    }
    const serviceCount = calendar.services.length;
    totalServices += serviceCount;

    console.log(`    ${serviceCount} services found.`);

    const expired: ExpiredEntry[] = [];
    const expiringSoon: ExpiringSoonEntry[] = [];
    const label = `${source.nameEn} (${source.prefix})`;

    for (const service of calendar.services) {
      const endDate = parseDate(service.e);
      const days = diffDays(today, endDate);

      if (days < 0) {
        expired.push({ source: label, serviceId: service.i, endDate: formatDate(endDate) });
      } else if (days <= WARN_THRESHOLD_DAYS) {
        expiringSoon.push({
          source: label,
          serviceId: service.i,
          endDate: formatDate(endDate),
          daysLeft: days,
        });
      }
    }

    // Find earliest end_date across all services for summary
    if (serviceCount > 0) {
      const earliest = calendar.services.reduce((min, s) => (s.e < min.e ? s : min));
      const earliestDate = parseDate(earliest.e);
      const earliestDays = diffDays(today, earliestDate);
      console.log(`    Earliest end_date: ${formatDate(earliestDate)} (${earliestDays} days left)`);
    } else {
      console.log('    Earliest end_date: N/A (no services)');
    }

    // Per-source result line
    if (expired.length === 0 && expiringSoon.length === 0) {
      console.log(`    Result: OK - all ${serviceCount} services valid.`);
    } else {
      if (expired.length > 0) {
        const earliestExpired = expired.reduce(
          (min, entry) => (entry.endDate < min ? entry.endDate : min),
          expired[0].endDate,
        );
        error(
          `${source.prefix}: ${expired.length} expired services (earliest ended ${earliestExpired})`,
        );
      }
      if (expiringSoon.length > 0) {
        warn(
          `${source.prefix}: ${expiringSoon.length} services expiring within ${WARN_THRESHOLD_DAYS} days`,
        );
      }
    }

    allExpired.push(...expired);
    allExpiringSoon.push(...expiringSoon);
  }

  console.log(
    `  Result: ${totalServices} services checked, ${allExpired.length} expired, ${allExpiringSoon.length} expiring soon.`,
  );

  return { totalServices, expired: allExpired, expiringSoon: allExpiringSoon, loadErrors };
}

/**
 * Print a Markdown summary of all validation results.
 * Designed for GitHub Actions Job Summary output.
 *
 * @param today - Current date (UTC midnight)
 * @param fileResult - File existence check result
 * @param calendarResult - Calendar freshness check result
 */
function printSummary(
  today: Date,
  fileResult: FileCheckResult,
  calendarResult: CalendarCheckResult,
): void {
  console.log('## Generated Data Validation\n');
  console.log(`Checked on: ${formatDate(today)}\n`);

  // File existence issues
  if (fileResult.missing.length > 0) {
    console.log('### ❌ Missing files\n');
    console.log('| Source | File |');
    console.log('|--------|------|');
    for (const m of fileResult.missing) {
      console.log(`| ${sanitize(m.source)} | ${sanitize(m.file)} |`);
    }
    console.log('');
  }

  // Calendar issues
  if (calendarResult.expired.length > 0) {
    console.log('### ❌ Expired services\n');
    console.log('| Source | Service ID | End Date |');
    console.log('|--------|-----------|----------|');
    for (const e of calendarResult.expired) {
      console.log(`| ${sanitize(e.source)} | \`${sanitize(e.serviceId)}\` | ${e.endDate} |`);
    }
    console.log('');
  }

  if (calendarResult.expiringSoon.length > 0) {
    console.log(`### ⚠️ Expiring within ${WARN_THRESHOLD_DAYS} days\n`);
    console.log('| Source | Service ID | End Date | Days Left |');
    console.log('|--------|-----------|----------|-----------|');
    for (const e of calendarResult.expiringSoon) {
      console.log(
        `| ${sanitize(e.source)} | \`${sanitize(e.serviceId)}\` | ${e.endDate} | ${e.daysLeft} |`,
      );
    }
    console.log('');
  }

  const hasErrors =
    fileResult.missing.length > 0 ||
    calendarResult.expired.length > 0 ||
    calendarResult.loadErrors > 0;
  const hasWarnings = calendarResult.expiringSoon.length > 0;

  if (hasErrors) {
    console.log('❌ Validation failed.\n');
  } else if (hasWarnings) {
    console.log('⚠️ Validation passed with warnings.\n');
  } else {
    console.log('✅ All checks passed.\n');
  }
}

/**
 * Determine the process exit code based on validation results.
 *
 * @param fileResult - File existence check result
 * @param calendarResult - Calendar freshness check result
 * @returns EXIT_OK (0), EXIT_WARN (1), or EXIT_ERROR (2)
 */
function determineExitCode(
  fileResult: FileCheckResult,
  calendarResult: CalendarCheckResult,
): number {
  if (
    fileResult.missing.length > 0 ||
    calendarResult.expired.length > 0 ||
    calendarResult.loadErrors > 0
  ) {
    return EXIT_ERROR;
  }
  if (calendarResult.expiringSoon.length > 0) {
    return EXIT_WARN;
  }
  return EXIT_OK;
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function printUsage(): void {
  console.log('Usage: npx tsx pipeline/scripts/validate-generated-data.ts');
  console.log('       npm run pipeline:validate');
  console.log('');
  console.log('Validate generated web app data files.');
  console.log('');
  console.log('Options:');
  console.log('  --help, -h   Show this help message');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const arg = process.argv[2];
  if (arg) {
    if (arg === '--help' || arg === '-h') {
      printUsage();
      return;
    }
    console.error(`Error: Unknown argument: ${arg}\n`);
    printUsage();
    process.exitCode = 1;
    return;
  }

  const startTime = performance.now();
  const now = new Date();
  const today = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));

  console.log(`=== Validate generated data (${DATA_DIR}) ===\n`);

  const sources = await loadSources();

  if (sources.length === 0) {
    warn('No GTFS source definitions found.');
    console.log('## Generated Data Validation\n');
    console.log('> **Warning**: No GTFS source definitions found.\n');
    process.exitCode = EXIT_WARN;
    return;
  }

  // Step 1: File existence check
  console.log('--- [1/2] File existence check ---\n');
  const fileResult = checkFileExistence(sources);
  console.log('');

  // Step 2: Calendar freshness check
  console.log('--- [2/2] Calendar freshness check ---\n');
  const calendarResult = checkCalendarFreshness(sources, today);
  console.log('');

  // Markdown summary
  printSummary(today, fileResult, calendarResult);

  const exitCode = determineExitCode(fileResult, calendarResult);
  const elapsed = Math.round(performance.now() - startTime);
  console.log(`Done in ${elapsed}ms. (exit code: ${exitCode})`);
  process.exitCode = exitCode;
}

// This script uses exit codes 0 (ok), 1 (warnings), and 2 (errors).
// runMain defaults to exitCode=1 on unhandled errors, but this script's
// contract requires EXIT_ERROR (2) for fatal failures, so we override it.
runMain(main, { fatalExitCode: EXIT_ERROR });
