import type { SourceGroup } from '../types/app/source-group';

const settings: SourceGroup[] = [
  {
    id: 'toei-bus',
    prefixes: ['minkuru'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Toei Bus', names: { ja: '都バス', en: 'Toei Bus' } },
    countries: ['JP'],
  },
  {
    id: 'toei-train',
    prefixes: ['toaran'],
    routeTypes: [0, 1, 2],
    enabled: true,
    name: { name: 'Toei', names: { ja: '都営交通', en: 'Toei' } },
    countries: ['JP'],
  },
  {
    id: 'yurikamome',
    prefixes: ['yurimo'],
    routeTypes: [2],
    enabled: true,
    name: { name: 'Yurikamome', names: { ja: 'ゆりかもめ', en: 'Yurikamome' } },
    countries: ['JP'],
  },
  {
    id: 'kanto-bus',
    prefixes: ['ktbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Kanto Bus', names: { ja: '関東バス', en: 'Kanto Bus' } },
    countries: ['JP'],
  },
  {
    id: 'keio-bus',
    prefixes: ['kobus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Keio Bus', names: { ja: '京王バス', en: 'Keio Bus' } },
    countries: ['JP'],
  },
  {
    id: 'chiyoda-bus',
    prefixes: ['kazag'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Kazaguruma', names: { ja: '風ぐるま', en: 'Kazaguruma' } },
    countries: ['JP'],
  },
  {
    id: 'chuo-bus',
    prefixes: ['edobus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Edo Bus', names: { ja: '江戸バス', en: 'Edo Bus' } },
    countries: ['JP'],
  },
  {
    id: 'suginami-gsm',
    prefixes: ['sggsm'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Sugimaru', names: { ja: 'すぎ丸', en: 'Sugimaru' } },
    countries: ['JP'],
  },
  // リソース定義最終確認中
  {
    id: 'seibu-bus',
    prefixes: ['sbbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Seibu Bus', names: { ja: '西武バス', en: 'Seibu Bus' } },
    countries: ['JP'],
  },
  {
    id: 'iyotetsu-bus',
    prefixes: ['iyt2'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Iyotetsu Bus', names: { ja: '伊予鉄バス', en: 'Iyotetsu Bus' } },
    countries: ['JP'],
  },
  {
    id: 'kita-bus',
    prefixes: ['kbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'K-bus', names: { ja: 'Kバス', en: 'K-bus' } },
    countries: ['JP'],
  },
  {
    id: 'kyoto-city-bus',
    prefixes: ['kcbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Kyoto City Bus', names: { ja: '京都市バス', en: 'Kyoto City Bus' } },
    countries: ['JP'],
  },
  {
    id: 'oshima-bus',
    prefixes: ['osmbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Oshima Bus', names: { ja: '大島バス', en: 'Oshima Bus' } },
    countries: ['JP'],
  },
  {
    id: 'miyake-bus',
    prefixes: ['mykbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Miyake Village Bus', names: { ja: '三宅村営バス', en: 'Miyake Village Bus' } },
    countries: ['JP'],
  },
  {
    id: 'keisei-transit-bus',
    prefixes: ['kseiw'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Keisei Transit Bus', names: { ja: '京成千葉W', en: 'Keisei Transit Bus' } },
    countries: ['JP'],
  },
  {
    id: 'nishi-tokyo-bus',
    prefixes: ['ntbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Nishi Tokyo Bus', names: { ja: '西東京バス', en: 'Nishi Tokyo Bus' } },
    countries: ['JP'],
  },
  {
    id: 'mir-train',
    prefixes: ['mir'],
    routeTypes: [2],
    enabled: true,
    name: { name: 'Tsukuba Express', names: { ja: 'TX', en: 'Tsukuba Express' } },
    countries: ['JP'],
  },
  {
    id: 'nagoya-srt',
    prefixes: ['nsrt'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Nagoya SRT', names: { ja: 'SRT名古屋', en: 'Nagoya SRT' } },
    countries: ['JP'],
  },
  {
    id: 'tama-monorail',
    prefixes: ['tmm'],
    routeTypes: [12],
    enabled: true,
    name: { name: 'Tama Monorail', names: { ja: '多摩モノレール', en: 'Tama Monorail' } },
    countries: ['JP'],
  },
  {
    id: 'twr-rinkai',
    prefixes: ['twrr'],
    routeTypes: [1, 2],
    enabled: true,
    name: {
      name: 'TWR Rinkai Line',
      names: { ja: 'りんかい線', en: 'TWR Rinkai Line' },
    },
    countries: ['JP'],
  },
  {
    id: 'tokyometro',
    prefixes: ['tome'],
    routeTypes: [1],
    enabled: true,
    name: { name: 'Tokyo Metro', names: { ja: '東京メトロ', en: 'Tokyo Metro' } },
    countries: ['JP'],
  },
  {
    id: 'actv-nav',
    prefixes: ['actvnav'],
    routeTypes: [4],
    enabled: true,
    name: { name: 'ACTV', names: { ja: 'ACTV', en: 'ACTV', it: 'ACTV' } },
    countries: ['IT'],
  },
  {
    id: 'tokyo-cruise-ship',
    prefixes: ['tcship'],
    routeTypes: [4],
    enabled: true,
    name: {
      name: 'Tokyo Cruise',
      names: { ja: '水上バス', en: 'Tokyo Cruise' },
    },
    countries: ['JP'],
  },
  {
    id: 'sanwa-shosen',
    prefixes: ['snws'],
    routeTypes: [4],
    enabled: true,
    name: {
      name: 'Sanwa Shosen',
      names: { ja: '三和商船', en: 'Sanwa Shosen' },
    },
    countries: ['JP'],
  },
  {
    id: 'tokai-kisen',
    prefixes: ['tkksn'],
    routeTypes: [4],
    enabled: true,
    name: {
      name: 'Tokai Kisen',
      names: { ja: '東海汽船', en: 'Tokai Kisen' },
    },
    countries: ['JP'],
  },
  {
    id: 'kagoshima-maritime-bureau',
    prefixes: ['kcmb'],
    routeTypes: [4],
    enabled: true,
    name: {
      name: 'Sakurajima Ferry',
      names: { ja: '桜島フェリー', en: 'Sakurajima Ferry' },
    },
    countries: ['JP'],
  },
  {
    id: 'okushiri-ferry',
    prefixes: ['oksrif'],
    routeTypes: [4],
    enabled: true,
    name: {
      name: 'Okushiri Island Ferry',
      names: { ja: '奥尻島フェリー', en: 'Okushiri Island Ferry' },
    },
    countries: ['JP'],
  },
  {
    id: 'orange-ferry',
    prefixes: ['orgfry'],
    routeTypes: [4],
    enabled: true,
    name: {
      name: 'Orange Ferry',
      names: { ja: 'オレンジフェリー', en: 'Orange Ferry' },
    },
    countries: ['JP'],
  },
  {
    id: 'uwajima-unyu',
    prefixes: ['uwjmfry'],
    routeTypes: [4],
    enabled: true,
    name: {
      name: 'Uwajima Unyu Ferries',
      names: { ja: '宇和島運輸フェリー', en: 'Uwajima Unyu Ferries' },
    },
    countries: ['JP'],
  },
  {
    id: 'meimon-taiyo-ferry',
    prefixes: ['mtfry'],
    routeTypes: [4],
    enabled: true,
    name: {
      name: 'Meimon Taiyo Ferry',
      names: { ja: '名門大洋フェリー', en: 'Meimon Taiyo Ferry' },
    },
    countries: ['JP'],
  },
  {
    id: 'itsukishima-kisen',
    prefixes: ['itkfry'],
    routeTypes: [4],
    enabled: true,
    name: {
      name: 'Itsukishima Kisen',
      names: { ja: '斎島汽船', en: 'Itsukishima Kisen' },
    },
    countries: ['JP'],
  },
  {
    id: 'vag-freiburg',
    prefixes: ['vagfr'],
    routeTypes: [0, 3],
    enabled: true,
    name: {
      name: 'VAG Freiburg',
      names: { ja: 'VAG Freiburg', en: 'VAG Freiburg', de: 'VAG Freiburg' },
    },
    countries: ['DE'],
  },
];

export default settings;
