import type { SourceGroup } from './data-source-manager';

const settings: SourceGroup[] = [
  {
    id: 'toei-bus',
    prefixes: ['minkuru'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Toei Bus', names: { ja: '都バス', en: 'Toei Bus' } },
  },
  {
    id: 'toei-train',
    prefixes: ['toaran'],
    routeTypes: [0, 1, 2],
    enabled: true,
    name: { name: 'Toei', names: { ja: '都営交通', en: 'Toei' } },
  },
  {
    id: 'yurikamome',
    prefixes: ['yurimo'],
    routeTypes: [2],
    enabled: true,
    name: { name: 'Yurikamome', names: { ja: 'ゆりかもめ', en: 'Yurikamome' } },
  },
  {
    id: 'kanto-bus',
    prefixes: ['ktbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Kanto Bus', names: { ja: '関東バス', en: 'Kanto Bus' } },
  },
  {
    id: 'keio-bus',
    prefixes: ['kobus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Keio Bus', names: { ja: '京王バス', en: 'Keio Bus' } },
  },
  {
    id: 'chiyoda-bus',
    prefixes: ['kazag'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Kazaguruma', names: { ja: '風ぐるま', en: 'Kazaguruma' } },
  },
  {
    id: 'chuo-bus',
    prefixes: ['edobus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Edo Bus', names: { ja: '江戸バス', en: 'Edo Bus' } },
  },
  {
    id: 'suginami-gsm',
    prefixes: ['sggsm'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Sugimaru', names: { ja: 'すぎ丸', en: 'Sugimaru' } },
  },
  // リソース定義最終確認中
  {
    id: 'seibu-bus',
    prefixes: ['sbbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Seibu Bus', names: { ja: '西武バス', en: 'Seibu Bus' } },
  },
  {
    id: 'iyotetsu-bus',
    prefixes: ['iyt2'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Iyotetsu Bus', names: { ja: '伊予鉄バス', en: 'Iyotetsu Bus' } },
  },
  {
    id: 'kita-bus',
    prefixes: ['kbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'K-bus', names: { ja: 'Kバス', en: 'K-bus' } },
  },
  {
    id: 'kyoto-city-bus',
    prefixes: ['kcbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Kyoto City Bus', names: { ja: '京都市バス', en: 'Kyoto City Bus' } },
  },
  {
    id: 'oshima-bus',
    prefixes: ['osmbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Oshima Bus', names: { ja: '大島バス', en: 'Oshima Bus' } },
  },
  {
    id: 'miyake-bus',
    prefixes: ['mykbus'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Miyake Village Bus', names: { ja: '三宅村営バス', en: 'Miyake Village Bus' } },
  },
  {
    id: 'keisei-transit-bus',
    prefixes: ['kseiw'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Keisei Transit Bus', names: { ja: '京成千葉W', en: 'Keisei Transit Bus' } },
  },
  {
    id: 'mir-train',
    prefixes: ['mir'],
    routeTypes: [2],
    enabled: true,
    name: { name: 'Tsukuba Express', names: { ja: 'TX', en: 'Tsukuba Express' } },
  },
  {
    id: 'nagoya-srt',
    prefixes: ['nsrt'],
    routeTypes: [3],
    enabled: true,
    name: { name: 'Nagoya SRT', names: { ja: 'SRT名古屋', en: 'Nagoya SRT' } },
  },
  {
    id: 'actv-nav',
    prefixes: ['actvnav'],
    routeTypes: [4],
    enabled: true,
    name: { name: 'ACTV', names: { ja: 'ACTV', en: 'ACTV', it: 'ACTV' } },
  },
  {
    id: 'vag-freiburg',
    prefixes: ['vagfr'],
    routeTypes: [0, 3],
    enabled: true,
    name: {
      name: 'VAG Freiburg',
      names: { ja: 'VAG Freiburg', en: 'VAG Freiburg', de: 'VAG Freiburg' },
    },
  },
];

export default settings;
