/**
 * Wire-format types for the next-generation pipeline output (v2).
 *
 * This file defines the target schema for the timetable.json and
 * trip-patterns.json redesign. The v1 types in transit-json.ts
 * remain in use until the pipeline and repository are migrated.
 *
 * Key changes from v1:
 * - TimetableGroupJson: `r, h, ai` replaced with `tp` (pattern FK).
 *   Adds `a` (arrival), `p` (pickup_type), `do` (drop_off_type).
 * - TripPatternsJson: new file providing route, headsign, direction,
 *   and ordered stop sequence per pattern.
 *
 * Types that are unchanged from v1 (StopJson, RouteJson, AgencyJson,
 * CalendarJson, TranslationsJson, ShapesJson, FeedInfoJson) are NOT
 * duplicated here — import them from transit-json.ts.
 */

// -----------------------------------------------------------------------
// trip-patterns.json
// -----------------------------------------------------------------------

/**
 * trip-patterns.json: pattern_id -> trip pattern metadata.
 *
 * A trip pattern represents a unique combination of route, headsign,
 * direction, and ordered stop sequence. Multiple trips (departures)
 * share the same pattern when they follow the same stops in the same
 * order.
 *
 * Pattern IDs are generated by the pipeline and are only guaranteed
 * to be consistent within a single build. All JSON files from the
 * same build are referentially consistent.
 *
 * Generated by the pipeline from:
 * - GTFS: derived by grouping trips with identical stop_sequences
 * - ODPT: derived from stationOrder + destinationStation
 *
 * Derivable information (not stored, computed by consumers):
 * - Origin stop: `stops[0]`
 * - Terminal stop: `stops[stops.length - 1]`
 * - Number of stops: `stops.length`
 * - Circular route: `stops[0] === stops[stops.length - 1]`
 * - Whether a stop is on this pattern: `stops.includes(stopId)`
 * - Stop position in pattern: `stops.indexOf(stopId)`
 *
 * Agency is not stored here — resolve via `r` -> RouteJson.ai.
 * GTFS spec defines route:agency as 1:1 (routes.txt.agency_id).
 */
export interface TripPatternsJson {
  /** Schema version. Must be `2` for this format. */
  v: 2;
  /** pattern_id -> trip pattern metadata */
  patterns: Record<string, TripPatternJson>;
}

export interface TripPatternJson {
  /** Schema version. Must be `2` for this format. */
  v: 2;

  /**
   * Route ID (prefixed). FK -> routes.json.
   * All trips in this pattern belong to this route.
   */
  r: string;

  /**
   * Trip headsign (destination display text from GTFS trip_headsign).
   *
   * May be empty when the GTFS source does not provide trip_headsign
   * (e.g. keio-bus). In that case, consumers can derive a display
   * name from the terminal stop: `stops[stops.length - 1]` ->
   * StopJson.n or translations.
   */
  h: string;

  /**
   * GTFS direction_id (0 or 1).
   *
   * Distinguishes trips that share the same route and headsign but
   * travel in opposite directions. Required for circular routes
   * such as the Oedo Line, where both inner and outer loops have
   * the same headsign ("都庁前") but different stop sequences.
   *
   * Omitted when the source does not provide direction_id (e.g. ODPT).
   * GTFS spec: "should not be used in routing; provides a way to
   * separate trips by direction when publishing time tables."
   */
  dir?: number;

  /**
   * Ordered stop IDs (prefixed) from origin to destination.
   *
   * - `stops[0]` is the first stop (origin).
   * - `stops[stops.length - 1]` is the terminal.
   * - The order represents the actual stop sequence of the trip.
   * - Consumers MUST NOT re-sort this array.
   *
   * Derived from GTFS stop_times (ORDER BY stop_sequence) or
   * ODPT stationOrder filtered by destinationStation.
   */
  stops: string[];
}

// -----------------------------------------------------------------------
// timetable.json (v2)
// -----------------------------------------------------------------------

/**
 * timetable.json (v2): versioned wrapper with stop_id -> schedule groups.
 *
 * Each group references a trip pattern and contains departure/arrival
 * times keyed by service_id. A single stop may have multiple groups
 * for the same route+headsign when different trip patterns pass
 * through it (e.g. 宿91 新宿駅西口行き has 3 patterns with different
 * origins). Consumers that need route+headsign grouping (e.g.
 * DepartureGroup) must re-aggregate across patterns.
 */
export interface TimetableV2Json {
  /** Schema version. Must be `2` for this format. */
  v: 2;
  /** stop_id -> schedule groups */
  stops: Record<string, TimetableGroupV2Json[]>;
}

export interface TimetableGroupV2Json {
  /** Schema version. Must be `2` for this format. */
  v: 2;

  /**
   * Trip pattern ID. FK -> trip-patterns.json.
   * Resolves to route_id, headsign, direction, and stop sequence.
   * Agency is further resolved via TripPatternJson.r -> RouteJson.ai.
   */
  tp: string;

  /**
   * Service ID -> sorted departure minutes from midnight.
   * Minutes >= 1440 represent overnight departures past midnight.
   */
  d: Record<string, number[]>;

  /**
   * Service ID -> sorted arrival minutes from midnight.
   * Parallel to {@link d}: `a[serviceId][i]` corresponds to
   * `d[serviceId][i]`. When arrival equals departure (most bus
   * stops), the same value is stored in both arrays.
   *
   * For ODPT sources that do not provide arrival times, values
   * are copied from departure times.
   */
  a: Record<string, number[]>;

  /**
   * Service ID -> pickup_type per departure.
   * Parallel to {@link d}: `p[serviceId][i]` corresponds to
   * `d[serviceId][i]`.
   *
   * GTFS pickup_type: 0 = regular, 1 = no pickup (drop-off only),
   * 2 = must phone, 3 = must coordinate with driver.
   *
   * Omitted when all departures in this group have pickup_type = 0.
   */
  p?: Record<string, number[]>;

  /**
   * Service ID -> drop_off_type per departure.
   * Parallel to {@link d}: `do[serviceId][i]` corresponds to
   * `d[serviceId][i]`.
   *
   * GTFS drop_off_type: 0 = regular, 1 = no drop-off (pickup only),
   * 2 = must phone, 3 = must coordinate with driver.
   *
   * Omitted when all departures in this group have drop_off_type = 0.
   */
  do?: Record<string, number[]>;
}
